application:
  actions: actions
  runtimeManifest:
    packages:
      graybox:
        license: Apache-2.0
        actions:            
          promote:
            function: actions/graybox/promote.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug  
          promote-worker:
            function: actions/graybox/promote-worker.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 2048
