application:
  actions: actions
  runtimeManifest:
    packages:
      graybox:
        license: Apache-2.0
        inputs:
          spSite: $SP_SITE
          spClientId: $SP_CLIENT_ID
          spAuthority: $SP_AUTHORITY
          clientId: $CLIENT_ID
          tenantId: $TENANT_ID
          certPassword: $CERT_PASSWORD
          certKey: $CERT_KEY
          certThumbprint: $CERT_THUMB_PRINT
          enablePreview: $ENABLE_PREVIEW
          groupCheckUrl: $GROUP_CHECK_URL
          grayboxUserGroups: $GRAYBOX_USER_GROUPS
          helixAdminApiKeys: $HELIX_ADMIN_API_KEYS
          bulkPreviewCheckInterval: $BULK_PREVIEW_CHECK_INTERVAL
          maxBulkPreviewChecks: $MAX_BULK_PREVIEW_CHECKS
        actions:            
          promote:
            function: actions/graybox/promote.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
          initiate-promote-worker:
            function: actions/graybox/initiate-promote-worker.js
            web: 'no'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 2048
          preview-worker:
            function: actions/graybox/preview-worker.js
            web: 'no'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 2048
          process-docx-worker:
            function: actions/graybox/process-docx-worker.js
            web: 'no'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 2048
          promote-worker:
            function: actions/graybox/promote-worker.js
            web: 'no'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 2048
          copy-worker:
            function: actions/graybox/copy-worker.js
            web: 'no'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 2048
          pause-project-in-queue:
            function: actions/graybox/pause-project-in-queue.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
          file-status:
            function: actions/graybox/file-status.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
          keys-check:
            function: actions/graybox/keys-check.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
          preview-sched:
            function: actions/graybox/preview-sched.js
            web: 'no'
            runtime: 'nodejs:18'
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 900000
              memorySize: 2048
            annotations:
              require-adobe-auth: false
              final: true              
          process-docx-sched:
            function: actions/graybox/process-docx-sched.js
            web: 'no'
            runtime: 'nodejs:18'
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 900000
              memorySize: 2048
            annotations:
              require-adobe-auth: false
              final: true              
          promote-sched:
            function: actions/graybox/promote-sched.js
            web: 'no'
            runtime: 'nodejs:18'
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 900000
              memorySize: 2048
            annotations:
              require-adobe-auth: false
              final: true              
          copy-sched:
            function: actions/graybox/copy-sched.js
            web: 'no'
            runtime: 'nodejs:18'
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 900000
              memorySize: 2048
            annotations:
              require-adobe-auth: false
              final: true              
        triggers:
          everyMin:
            feed: /whisk.system/alarms/interval
            inputs:
              minutes: 1
        rules:
          everyMinRule:
            trigger: everyMin
            action: preview-sched
          everyMinProcessDocxRule:
            trigger: everyMin
            action: process-docx-sched
          everyMinPromoteDocxRule:
            trigger: everyMin
            action: promote-sched
          everyMinCopyDocxRule:
            trigger: everyMin
            action: copy-sched
