application:
  actions: actions
  runtimeManifest:
    packages:
      graybox:
        license: Apache-2.0
        inputs:
          spSite: $SP_SITE
          spClientId: $SP_CLIENT_ID
          spAuthority: $SP_AUTHORITY
          clientId: $CLIENT_ID
          tenantId: $TENANT_ID
          certPassword: $CERT_PASSWORD
          certKey: $CERT_KEY
          certThumbprint: $CERT_THUMB_PRINT
          enablePreview: $ENABLE_PREVIEW
          groupCheckUrl: $GROUP_CHECK_URL
          grayboxUserGroups: $GRAYBOX_USER_GROUPS
          helixAdminApiKeys: $HELIX_ADMIN_API_KEYS
          bulkPreviewCheckInterval: $BULK_PREVIEW_CHECK_INTERVAL
          maxBulkPreviewChecks: $MAX_BULK_PREVIEW_CHECKS
        actions:            
          promote:
            function: actions/graybox/promote.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug  
          promote-worker:
            function: actions/graybox/promote-worker.js
            web: 'no'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 2048
